spring:
  application:
    name: Client Directory
  profiles:
    active: dev


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/client_directory
    username: admin
    password: admin
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
---

spring:
  config:
    activate:
      on-profile: prod